-- Extend AuditAction enum with package + firewall management events.
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_INSTALLED';
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE 'PACKAGE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'FIREWALL_RULE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE 'FIREWALL_RULE_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE 'FIREWALL_ENABLED';
ALTER TYPE "AuditAction" ADD VALUE 'FIREWALL_DISABLED';
